/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CafesImport } from './routes/cafes'

// Create Virtual Routes

const EmployeesLazyImport = createFileRoute('/employees')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const EmployeesLazyRoute = EmployeesLazyImport.update({
  path: '/employees',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/employees.lazy').then((d) => d.Route))

const CafesRoute = CafesImport.update({
  path: '/cafes',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesImport
      parentRoute: typeof rootRoute
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cafes': typeof CafesRoute
  '/employees': typeof EmployeesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cafes': typeof CafesRoute
  '/employees': typeof EmployeesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cafes': typeof CafesRoute
  '/employees': typeof EmployeesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cafes' | '/employees'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cafes' | '/employees'
  id: '__root__' | '/' | '/cafes' | '/employees'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CafesRoute: typeof CafesRoute
  EmployeesLazyRoute: typeof EmployeesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CafesRoute: CafesRoute,
  EmployeesLazyRoute: EmployeesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cafes",
        "/employees"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cafes": {
      "filePath": "cafes.tsx"
    },
    "/employees": {
      "filePath": "employees.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
